# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
# created-by: conda 25.5.1
_libgcc_mutex=0.1=main
_openmp_mutex=5.1=1_gnu
_python_abi3_support=1.0=hd8ed1ab_2
alsa-lib=1.2.15.3=hb03c661_0
altair=6.0.0=pypi_0
annotated-types=0.7.0=pyhd8ed1ab_1
anyio=4.12.1=pyhcf101f3_0
argon2-cffi=25.1.0=pyhd8ed1ab_0
argon2-cffi-bindings=25.1.0=py313h07c4f96_2
arrow=1.4.0=pyhcf101f3_0
asttokens=3.0.1=pyhd8ed1ab_0
async-lru=2.1.0=pyhcf101f3_0
attrs=25.4.0=pyhcf101f3_1
autopep8=2.3.2=pypi_0
babel=2.17.0=pyhd8ed1ab_0
backports.zstd=1.3.0=py313h18e8e13_0
beautifulsoup4=4.14.3=pyha770c72_0
bleach=6.3.0=pyhcf101f3_0
bleach-with-css=6.3.0=h5f6438b_0
brotli=1.2.0=hed03a55_1
brotli-bin=1.2.0=hb03c661_1
brotli-python=1.2.0=py313hf159716_1
bzip2=1.0.8=h5eee18b_6
ca-certificates=2026.1.4=hbd8a1cb_0
cached-property=1.5.2=hd8ed1ab_1
cached_property=1.5.2=pyha770c72_1
cairo=1.18.0=hbb29018_2
certifi=2026.1.4=pyhd8ed1ab_0
cffi=1.17.1=py313hfab6e84_0
charset-normalizer=3.4.4=pyhd8ed1ab_0
colorama=0.4.6=pyhd8ed1ab_1
comm=0.2.3=pyhe01879c_0
contourpy=1.3.3=py313hc8edb43_4
cpython=3.13.11=py313hd8ed1ab_100
cycler=0.12.1=pyhcf101f3_2
dacite=1.9.2=pyhd8ed1ab_0
dataclasses=0.8=pyhc8e2a94_3
dbt=1.0.0.40.14=pypi_0
dbus=1.13.6=h5008d03_3
debugpy=1.8.19=py313hb7f33ac_0
decorator=5.2.1=pyhd8ed1ab_0
defusedxml=0.7.1=pyhd8ed1ab_0
double-conversion=3.3.1=h5888daf_0
exceptiongroup=1.3.1=pyhd8ed1ab_0
executing=2.2.1=pyhd8ed1ab_0
expat=2.7.3=h7354ed3_4
filetype=1.2.0=pyhd8ed1ab_0
font-ttf-dejavu-sans-mono=2.37=hab24e00_0
font-ttf-inconsolata=3.000=h77eed37_0
font-ttf-source-code-pro=2.038=h77eed37_0
font-ttf-ubuntu=0.83=h77eed37_3
fontconfig=2.15.0=h2c49b7f_0
fonts-conda-ecosystem=1=0
fonts-conda-forge=1=hc364b38_1
fonttools=4.61.1=py313h3dea7bd_0
fqdn=1.5.1=pyhd8ed1ab_1
freetype=2.14.1=ha770c72_0
graphite2=1.3.14=hecca717_2
h11=0.16.0=pyhcf101f3_1
h2=4.3.0=pyhcf101f3_0
harfbuzz=9.0.0=hfac3d4d_0
hpack=4.1.0=pyhd8ed1ab_0
httpcore=1.0.9=pyh29332c3_0
httpx=0.28.1=pyhd8ed1ab_0
hyperframe=6.1.0=pyhd8ed1ab_0
icu=73.2=h59595ed_0
idna=3.11=pyhd8ed1ab_0
imagehash=4.3.2=pyhd8ed1ab_0
importlib-metadata=8.7.0=pyhe01879c_1
importlib_resources=6.5.2=pyhd8ed1ab_0
ipykernel=7.1.0=pyha191276_0
ipython=9.9.0=pyh53cf698_0
ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
ipywidgets=8.1.8=pyhd8ed1ab_0
iso3166=2.1.1=pypi_0
isoduration=20.11.0=pyhd8ed1ab_1
jedi=0.19.2=pyhd8ed1ab_1
jinja2=3.1.6=pyhcf101f3_1
joblib=1.5.3=pyhd8ed1ab_0
json5=0.13.0=pyhd8ed1ab_0
jsonpointer=3.0.0=pyhcf101f3_3
jsonschema=4.26.0=pyhcf101f3_0
jsonschema-specifications=2025.9.1=pyhcf101f3_0
jsonschema-with-format-nongpl=4.26.0=hcf101f3_0
jupyter-lsp=2.3.0=pyhcf101f3_0
jupyter_client=8.8.0=pyhcf101f3_0
jupyter_core=5.9.1=pyhc90fa1f_0
jupyter_events=0.12.0=pyh29332c3_0
jupyter_server=2.17.0=pyhcf101f3_0
jupyter_server_terminals=0.5.4=pyhcf101f3_0
jupyterlab=4.5.3=pyhd8ed1ab_0
jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
jupyterlab_server=2.28.0=pyhcf101f3_0
jupyterlab_widgets=3.0.16=pyhcf101f3_1
keyutils=1.6.3=hb9d3cd8_0
kiwisolver=1.4.9=py313hc8edb43_2
krb5=1.21.3=h659f571_0
lark=1.3.1=pyhd8ed1ab_0
lcms2=2.17=h717163a_0
ld_impl_linux-64=2.44=h153f514_2
lerc=4.0.0=h0aef613_1
libblas=3.11.0=5_h4a7cf45_openblas
libbrotlicommon=1.2.0=hb03c661_1
libbrotlidec=1.2.0=hb03c661_1
libbrotlienc=1.2.0=hb03c661_1
libcblas=3.11.0=5_h0358290_openblas
libclang-cpp18.1=18.1.8=default_h99862b1_17
libclang13=21.1.0=default_h746c552_1
libcups=2.3.3=hb8b1518_5
libdeflate=1.22=hb9d3cd8_0
libdrm=2.4.125=hb03c661_1
libedit=3.1.20250104=pl5321h7949ede_0
libegl=1.7.0=ha4b6fd6_2
libexpat=2.7.3=h7354ed3_4
libffi=3.4.4=h6a678d5_1
libfreetype=2.14.1=ha770c72_0
libfreetype6=2.14.1=h73754d4_0
libgcc=15.2.0=h69a1729_7
libgcc-ng=15.2.0=h166f726_7
libgfortran=15.2.0=h69a702a_16
libgfortran5=15.2.0=h68bc16d_16
libgl=1.7.0=ha4b6fd6_2
libglib=2.80.2=hf974151_0
libglvnd=1.7.0=ha4b6fd6_2
libglx=1.7.0=ha4b6fd6_2
libgomp=15.2.0=h4751f2c_7
libiconv=1.18=h3b78370_2
libjpeg-turbo=3.1.2=hb03c661_0
liblapack=3.11.0=5_h47877c9_openblas
libllvm18=18.1.8=default_hddf928d_9
libllvm21=21.1.0=hecd9e04_0
libmpdec=4.0.0=h5eee18b_0
libopenblas=0.3.30=pthreads_h94d23a6_4
libopengl=1.7.0=ha4b6fd6_2
libpciaccess=0.18=hb9d3cd8_0
libpng=1.6.54=h421ea60_0
libpq=16.11=hc183893_2
libsodium=1.0.20=h4ab18f5_0
libsqlite=3.51.2=h0c1763c_0
libstdcxx=15.2.0=h39759b7_7
libstdcxx-ng=15.2.0=hc03a8fd_7
libtiff=4.7.0=he137b08_1
libuuid=1.41.5=h5eee18b_0
libwebp-base=1.6.0=hd42ef1d_0
libxcb=1.17.0=h9b100fa_0
libxkbcommon=1.11.0=he8b52b9_0
libxml2=2.13.9=h2c43086_0
libxslt=1.1.43=h7a3aeb2_0
libzlib=1.3.1=hb25bd0a_0
llvmlite=0.45.1=py313hdd307be_0
lux=0.5.1=pypi_0
lux-api=0.5.1=pypi_0
lux-widget=0.1.11=pypi_0
markupsafe=3.0.3=py313h3dea7bd_0
matplotlib=3.10.0=py313h78bf25f_0
matplotlib-base=3.10.0=py313h129903b_0
matplotlib-inline=0.2.1=pyhd8ed1ab_0
minify-html=0.18.1=py313h5c7d99a_0
mistune=3.2.0=pyhcf101f3_0
multimethod=1.12=pyhd8ed1ab_1
munkres=1.1.4=pyhd8ed1ab_1
mysql-common=8.3.0=h70512c7_5
mysql-libs=8.3.0=ha479ceb_5
narwhals=2.15.0=pypi_0
nbclient=0.10.4=pyhd8ed1ab_0
nbconvert-core=7.16.6=pyhcf101f3_1
nbformat=5.10.4=pyhd8ed1ab_1
ncurses=6.5=h7934f7d_0
nest-asyncio=1.6.0=pyhd8ed1ab_1
networkx=3.6.1=pyhcf101f3_0
notebook=7.5.2=pyhcf101f3_0
notebook-shim=0.2.4=pyhd8ed1ab_1
numba=0.62.1=py313h7afe1cf_1
numpy=2.3.5=py313hf6604e3_1
openjpeg=2.5.3=h55fea9a_1
openssl=3.6.0=h26f9b46_0
overrides=7.7.0=pyhd8ed1ab_1
packaging=26.0=pyhcf101f3_0
pandas=2.3.3=py313h08cd8bf_2
pandocfilters=1.5.0=pyhd8ed1ab_0
parso=0.8.5=pyhcf101f3_0
patsy=1.0.2=pyhcf101f3_0
pcre2=10.43=hcad00b1_0
pexpect=4.9.0=pyhd8ed1ab_1
phik=0.12.5=py313hc8edb43_1
pillow=11.3.0=py313ha492abd_3
pip=25.3=pyhc872135_0
pixman=0.46.4=h54a6638_1
platformdirs=4.5.1=pyhcf101f3_0
prometheus_client=0.24.1=pyhd8ed1ab_0
prompt-toolkit=3.0.52=pyha770c72_0
psutil=7.2.1=py313h54dd161_0
pthread-stubs=0.3=h0ce48e5_1
ptyprocess=0.7.0=pyhd8ed1ab_1
pure_eval=0.2.3=pyhd8ed1ab_1
puremagic=1.30=pyhe01879c_0
pycodestyle=2.14.0=pypi_0
pycparser=2.22=pyh29332c3_1
pydantic=2.12.5=pyhcf101f3_1
pydantic-core=2.41.5=py313h843e2db_1
pygments=2.19.2=pyhd8ed1ab_0
pyparsing=3.3.2=pyhcf101f3_0
pyside6=6.7.2=py313h5f61773_4
pysocks=1.7.1=pyha55dd90_7
python=3.13.11=hcf712cf_100_cp313
python-dateutil=2.9.0.post0=pyhe01879c_2
python-fastjsonschema=2.21.2=pyhe01879c_0
python-gil=3.13.11=h4df99d1_100
python-json-logger=2.0.7=pyhd8ed1ab_0
python-tzdata=2025.3=pyhd8ed1ab_0
python_abi=3.13=3_cp313
pytz=2025.2=pyhd8ed1ab_0
pywavelets=1.9.0=py313h29aa505_2
pyyaml=6.0.3=py313h3dea7bd_0
pyzmq=27.1.0=py312hfb55c3c_0
qhull=2020.2=h434a139_5
qt6-main=6.7.2=h7d13b96_3
readline=8.3=hc2a1206_0
referencing=0.37.0=pyhcf101f3_0
requests=2.32.5=pyhcf101f3_1
reverse-geocoder=1.5.1=pypi_0
rfc3339-validator=0.1.4=pyhd8ed1ab_1
rfc3986-validator=0.1.1=pyh9f0ad1d_0
rfc3987-syntax=1.1.0=pyhe01879c_1
rpds-py=0.30.0=py313h843e2db_0
scikit-learn=1.8.0=pypi_0
scipy=1.16.3=py313h4b8bb8b_2
seaborn=0.13.2=hd8ed1ab_3
seaborn-base=0.13.2=pyhd8ed1ab_3
send2trash=2.1.0=pyha191276_0
setuptools=80.9.0=py313h06a4308_0
sh=2.2.2=pypi_0
six=1.17.0=pyhe01879c_1
sniffio=1.3.1=pyhd8ed1ab_2
soupsieve=2.8.3=pyhd8ed1ab_0
sqlite=3.51.1=he0a8d7e_0
stack_data=0.6.3=pyhd8ed1ab_1
statsmodels=0.14.6=py313h29aa505_0
terminado=0.18.1=pyhc90fa1f_1
threadpoolctl=3.6.0=pypi_0
tinycss2=1.4.0=pypi_0
tk=8.6.15=h54e0aa7_0
tomli=2.4.0=pyhcf101f3_0
tornado=6.5.4=py313hd02dea0_0
tqdm=4.67.1=pyhd8ed1ab_1
traitlets=5.14.3=pyhd8ed1ab_1
typeguard=4.4.4=pyhd8ed1ab_0
typing-extensions=4.15.0=h396c80c_0
typing-inspection=0.4.2=pyhd8ed1ab_1
typing_extensions=4.15.0=pyhcf101f3_0
typing_utils=0.1.0=pyhd8ed1ab_1
tzdata=2025c=he532380_0
uri-template=1.3.0=pyhd8ed1ab_1
urllib3=2.6.3=pyhd8ed1ab_0
visions=0.8.1=pyhcf101f3_0
wayland=1.23.1=h3e06ad9_0
wcwidth=0.2.14=pyhd8ed1ab_0
webcolors=25.10.0=pyhd8ed1ab_0
webencodings=0.5.1=pyhd8ed1ab_3
websocket-client=1.9.0=pyhd8ed1ab_0
wheel=0.45.1=py313h06a4308_0
widgetsnbextension=4.0.15=pyhd8ed1ab_0
wordcloud=1.9.4=py313h07c4f96_2
xcb-util=0.4.1=h4f16b4b_2
xcb-util-cursor=0.1.6=hb03c661_0
xcb-util-image=0.4.0=hb711507_2
xcb-util-keysyms=0.4.1=hb711507_0
xcb-util-renderutil=0.3.10=hb711507_0
xcb-util-wm=0.4.2=hb711507_0
xkeyboard-config=2.46=hb03c661_0
xorg-libice=1.1.2=hb9d3cd8_0
xorg-libsm=1.2.6=h9b100fa_0
xorg-libx11=1.8.12=h9b100fa_1
xorg-libxau=1.0.12=h9b100fa_0
xorg-libxdmcp=1.1.5=h9b100fa_0
xorg-libxext=1.3.6=hb9d3cd8_0
xorg-libxrender=0.9.12=hb9d3cd8_0
xorg-xorgproto=2024.1=h5eee18b_1
xz=5.6.4=h5eee18b_1
yaml=0.2.5=h280c20c_3
ydata-profiling=4.18.1=pyhcf101f3_0
zeromq=4.3.5=h387f397_9
zipp=3.23.0=pyhcf101f3_1
zlib=1.3.1=hb25bd0a_0
zstd=1.5.7=hb78ec9c_6
